server:
  port: 8765

spring:
  application:
    name: api-gateway  # Nome da aplicação

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Perfil ativo (fall back para dev)

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/atendeia-realm

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}  # Configuração do Config Server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}  # Endereço do Eureka Server
    fetch-registry: true
    register-with-eureka: true

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
routes:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/usuarios/**

      - id: auth-service
        uri: lb://auth-service
        predicates:
          - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
