server:
  port: 0

spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: user-service-client
            client-secret: wAzW2s0lTpgjF4aZVAC0PxfPVOuHFMHK
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8180/realms/atendeia-realm/protocol/openid-connect/token

eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
    status-page-url-path: /actuator/health
    health-check-url-path: /actuator/health
    home-page-url-path: /
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    display-request-duration: true
  paths-to-exclude:
    - /actuator/**

